kind: Service
apiVersion: v1
metadata:
  name: godaddy-dns-updater-service
spec:
  selector:
    app: godaddy-dns-updater
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: godaddy-dns-updater
  labels:
    app: godaddy-dns-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: godaddy-dns-updater
  template:
    metadata:
      labels:
        app: godaddy-dns-updater
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: godaddy-dns-updater
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80